name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to latest version

      - name: Login to Docker Hub
        uses: docker/login-action@v3  # Updated to latest version
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated to latest version

      - name: Build and push
        uses: docker/build-push-action@v5  # Updated to latest version
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.
